hostname: octoprint
ansible_sudo_pass: p@ssword

octoprint_version: 1.3.1

octoprint_config_server_port: 5000
octoprint_flash: false
octoprint_config_webcam:
  stream: "http://{{ansible_all_ipv4_addresses[0]}}:8080/?action=stream"
  snapshot: "http://{{ansible_all_ipv4_addresses[0]}}:8080/?action=snapshot"
  ffmpeg: "/usr/bin/ffmpeg"
  watermark: true
  timelapse:
    type: "zchange"


